export class GridService {
  constructor() {
  }

  getGridColumns() {
    return ['BEGDOC', 'BEGATT', 'Custodian', 'Custodian All', 'Author From', 'Email To', 'Email CC', 'Email BCC', 'Title Subject',
      'Email Read Status', 'Email Folder', 'Email Type', 'File Type', 'File Category', 'Hidden Content', 'Languages Identified',
      'File Path Relative', 'Last Saved By', 'MM Data Location Source Type', 'Attorney Comments', 'Paralegal Comments'];
  }

  getRecords() {
    return {
      "Records": [
        {  
          "BEGDOC":"GLO_P00000033",
          "BEGATT":"GLO_P00000032",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000042",
          "BEGATT":"GLO_P00000038",
          "Custodian":"Ariana Akers; Cory Espinoza; Henrietta Becker; Rachael Dejesus; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000063",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000064",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000065",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000066",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000147",
          "BEGATT":"GLO_P00000146",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000160",
          "BEGATT":"GLO_P00000159",
          "Custodian":"Ariana Akers; Charley Hoover; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000247",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000248",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000249",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000250",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000263",
          "BEGATT":"GLO_P00000262",
          "Custodian":"Ariana Akers; Gabriela Downing; Jocelyn Jamison; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Dwight McMullen; Salvatore Charles;dmcmullen@globex.com; salvatore.charles@nixonstrategies.com;globex.com; nixonstrategies.com",
          "Email CC":null,
          "Email BCC":"Faith O'Hara; Gabriela Downing;fohara@globex.com; gdowning@globex.com;globex.com; globex.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000281",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000282",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000283",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000284",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000289",
          "BEGATT":"GLO_P00000287",
          "Custodian":"Ariana Akers; Bridget Andrews; Jocelyn Jamison; Rachael Dejesus",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000300",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000301",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000308",
          "BEGATT":"GLO_P00000307",
          "Custodian":"Ariana Akers; Bonnie Casillas; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000314",
          "BEGATT":"GLO_P00000313",
          "Custodian":"Ariana Akers; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Kristy McNeil; Savannah Solano; Support;kmcneil@globex.com; savannah.solano@universalexport.com; Support@globex.com;globex.com; universalexport.com; globex.com",
          "Email CC":null,
          "Email BCC":"Janis Dugan; Katrina Kenny; Sonya Bernal; Tiffany McCullough;jdugan@globex.com; kkenny@globex.com; sbernal@globex.com; tiffany.mccullough@universalexport.com;globex.com; globex.com; globex.com; universalexport.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000323",
          "BEGATT":"GLO_P00000317",
          "Custodian":"Ariana Akers; Cory Espinoza; Terrance Gross",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
        "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000328",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000329",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {  
          "BEGDOC":"GLO_P00000033",
          "BEGATT":"GLO_P00000032",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000042",
          "BEGATT":"GLO_P00000038",
          "Custodian":"Ariana Akers; Cory Espinoza; Henrietta Becker; Rachael Dejesus; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000063",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000064",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000065",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000066",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000147",
          "BEGATT":"GLO_P00000146",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000160",
          "BEGATT":"GLO_P00000159",
          "Custodian":"Ariana Akers; Charley Hoover; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000247",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000248",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000249",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000250",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000263",
          "BEGATT":"GLO_P00000262",
          "Custodian":"Ariana Akers; Gabriela Downing; Jocelyn Jamison; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Dwight McMullen; Salvatore Charles;dmcmullen@globex.com; salvatore.charles@nixonstrategies.com;globex.com; nixonstrategies.com",
          "Email CC":null,
          "Email BCC":"Faith O'Hara; Gabriela Downing;fohara@globex.com; gdowning@globex.com;globex.com; globex.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000281",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000282",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000283",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000284",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000289",
          "BEGATT":"GLO_P00000287",
          "Custodian":"Ariana Akers; Bridget Andrews; Jocelyn Jamison; Rachael Dejesus",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000300",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000301",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000308",
          "BEGATT":"GLO_P00000307",
          "Custodian":"Ariana Akers; Bonnie Casillas; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000314",
          "BEGATT":"GLO_P00000313",
          "Custodian":"Ariana Akers; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Kristy McNeil; Savannah Solano; Support;kmcneil@globex.com; savannah.solano@universalexport.com; Support@globex.com;globex.com; universalexport.com; globex.com",
          "Email CC":null,
          "Email BCC":"Janis Dugan; Katrina Kenny; Sonya Bernal; Tiffany McCullough;jdugan@globex.com; kkenny@globex.com; sbernal@globex.com; tiffany.mccullough@universalexport.com;globex.com; globex.com; globex.com; universalexport.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000323",
          "BEGATT":"GLO_P00000317",
          "Custodian":"Ariana Akers; Cory Espinoza; Terrance Gross",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
        "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000328",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000329",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {  
          "BEGDOC":"GLO_P00000033",
          "BEGATT":"GLO_P00000032",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000042",
          "BEGATT":"GLO_P00000038",
          "Custodian":"Ariana Akers; Cory Espinoza; Henrietta Becker; Rachael Dejesus; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000063",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000064",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000065",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000066",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000147",
          "BEGATT":"GLO_P00000146",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000160",
          "BEGATT":"GLO_P00000159",
          "Custodian":"Ariana Akers; Charley Hoover; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000247",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000248",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000249",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000250",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000263",
          "BEGATT":"GLO_P00000262",
          "Custodian":"Ariana Akers; Gabriela Downing; Jocelyn Jamison; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Dwight McMullen; Salvatore Charles;dmcmullen@globex.com; salvatore.charles@nixonstrategies.com;globex.com; nixonstrategies.com",
          "Email CC":null,
          "Email BCC":"Faith O'Hara; Gabriela Downing;fohara@globex.com; gdowning@globex.com;globex.com; globex.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000281",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000282",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000283",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000284",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000289",
          "BEGATT":"GLO_P00000287",
          "Custodian":"Ariana Akers; Bridget Andrews; Jocelyn Jamison; Rachael Dejesus",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000300",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000301",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000308",
          "BEGATT":"GLO_P00000307",
          "Custodian":"Ariana Akers; Bonnie Casillas; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000314",
          "BEGATT":"GLO_P00000313",
          "Custodian":"Ariana Akers; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Kristy McNeil; Savannah Solano; Support;kmcneil@globex.com; savannah.solano@universalexport.com; Support@globex.com;globex.com; universalexport.com; globex.com",
          "Email CC":null,
          "Email BCC":"Janis Dugan; Katrina Kenny; Sonya Bernal; Tiffany McCullough;jdugan@globex.com; kkenny@globex.com; sbernal@globex.com; tiffany.mccullough@universalexport.com;globex.com; globex.com; globex.com; universalexport.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000323",
          "BEGATT":"GLO_P00000317",
          "Custodian":"Ariana Akers; Cory Espinoza; Terrance Gross",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
        "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000328",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000329",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {  
          "BEGDOC":"GLO_P00000033",
          "BEGATT":"GLO_P00000032",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000042",
          "BEGATT":"GLO_P00000038",
          "Custodian":"Ariana Akers; Cory Espinoza; Henrietta Becker; Rachael Dejesus; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000063",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000064",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000065",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000066",
          "BEGATT":"GLO_P00000062",
          "Custodian":"Ariana Akers; Katrina Kenny; Reggie Woodward",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000147",
          "BEGATT":"GLO_P00000146",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000160",
          "BEGATT":"GLO_P00000159",
          "Custodian":"Ariana Akers; Charley Hoover; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000247",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000248",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000249",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000250",
          "BEGATT":"GLO_P00000246",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000263",
          "BEGATT":"GLO_P00000262",
          "Custodian":"Ariana Akers; Gabriela Downing; Jocelyn Jamison; Rosalie Machado",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Dwight McMullen; Salvatore Charles;dmcmullen@globex.com; salvatore.charles@nixonstrategies.com;globex.com; nixonstrategies.com",
          "Email CC":null,
          "Email BCC":"Faith O'Hara; Gabriela Downing;fohara@globex.com; gdowning@globex.com;globex.com; globex.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000281",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal; Steve Pritchett",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000282",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000283",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000284",
          "BEGATT":"GLO_P00000280",
          "Custodian":"Ariana Akers; Charley Hoover; Patrick Burris; Sonya Bernal",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000289",
          "BEGATT":"GLO_P00000287",
          "Custodian":"Ariana Akers; Bridget Andrews; Jocelyn Jamison; Rachael Dejesus",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000300",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000301",
          "BEGATT":"GLO_P00000299",
          "Custodian":"Ariana Akers; Charley Hoover",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000308",
          "BEGATT":"GLO_P00000307",
          "Custodian":"Ariana Akers; Bonnie Casillas; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000314",
          "BEGATT":"GLO_P00000313",
          "Custodian":"Ariana Akers; Katrina Kenny",
          "Custodian All":null,
          "Author From":null,
          "Email To":"Kristy McNeil; Savannah Solano; Support;kmcneil@globex.com; savannah.solano@universalexport.com; Support@globex.com;globex.com; universalexport.com; globex.com",
          "Email CC":null,
          "Email BCC":"Janis Dugan; Katrina Kenny; Sonya Bernal; Tiffany McCullough;jdugan@globex.com; kkenny@globex.com; sbernal@globex.com; tiffany.mccullough@universalexport.com;globex.com; globex.com; globex.com; universalexport.com",
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000323",
          "BEGATT":"GLO_P00000317",
          "Custodian":"Ariana Akers; Cory Espinoza; Terrance Gross",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
        "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000328",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        },
        {
          "BEGDOC":"GLO_P00000329",
          "BEGATT":"GLO_P00000327",
          "Custodian":"Ariana Akers; Charley Hoover; Henrietta Becker",
          "Custodian All":null,
          "Author From":null,
          "Email To":null,
          "Email CC":null,
          "Email BCC":null,
          "Title Subject":null,
          "Email Read Status":null,
          "Email Folder":null,
          "Email Type":null,
          "File Type":"Unknown format",
          "File Category":null,
          "Hidden Content":null,
          "Languages Identified":null,
          "File Path Relative":null,
          "Last Saved By":null,
          "MM Data Location Source Type":null,
          "Attorney Comments":null,
          "Paralegal Comments":null
        }
      ],
    }
  }
}
